name: ETL Flight Data

on:
    workflow_dispatch:
    schedule:
      - cron: "0 0,12 * * *"

jobs:
  etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r py/requirements.txt

      - name: Run Python script
        run: |
          python py/etl.py
          
      - name: commit files
        run: | 
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add -A
          git commit -m "updated records" || echo "no changes to commit"
          git push origin || echo "no changes to commit"